<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run() {
        // $this->call(UsersTableSeeder::class);
        \DB::table('egp_expedidos')->insert(['id'=>'1', 'expedido'=>'CHUQUISACA']);
        \DB::table('egp_expedidos')->insert(['id'=>'2', 'expedido'=>'LA PAZ']);
        \DB::table('egp_expedidos')->insert(['id'=>'3', 'expedido'=>'COCHABAMBA']);
        \DB::table('egp_expedidos')->insert(['id'=>'4', 'expedido'=>'ORURO']);
        \DB::table('egp_expedidos')->insert(['id'=>'5', 'expedido'=>'POTOSI']);
        \DB::table('egp_expedidos')->insert(['id'=>'6', 'expedido'=>'TARIJA']);
        \DB::table('egp_expedidos')->insert(['id'=>'7', 'expedido'=>'SANTA CRUZ']);
        \DB::table('egp_expedidos')->insert(['id'=>'8', 'expedido'=>'BENI']);
        \DB::table('egp_expedidos')->insert(['id'=>'9', 'expedido'=>'PANDO']);
        \DB::table('egp_expedidos')->insert(['id'=>'26', 'expedido'=>'EXTRANJERO']);
        \DB::table('egp_expedidos')->insert(['id'=>'33', 'expedido'=>'OTROS']);
        \DB::table('egp_expedidos')->insert(['id'=>'34', 'expedido'=>'SIN DEFINIR']);

        \DB::table('egp_ciudads')->insert(['id'=>'376', 'ciudad'=>'BE - BAURES']);
        \DB::table('egp_ciudads')->insert(['id'=>'36', 'ciudad'=>'BE - BENI']);
        \DB::table('egp_ciudads')->insert(['id'=>'377', 'ciudad'=>'BE - EXALTACION']);
        \DB::table('egp_ciudads')->insert(['id'=>'40', 'ciudad'=>'BE - GUAYARAMERIN']);
        \DB::table('egp_ciudads')->insert(['id'=>'84', 'ciudad'=>'BE - HUACARAJE']);
        \DB::table('egp_ciudads')->insert(['id'=>'83', 'ciudad'=>'BE - LORETO']);
        \DB::table('egp_ciudads')->insert(['id'=>'88', 'ciudad'=>'BE - MAGDALENA']);
        \DB::table('egp_ciudads')->insert(['id'=>'378', 'ciudad'=>'BE - PUERTO SILES']);
        \DB::table('egp_ciudads')->insert(['id'=>'38', 'ciudad'=>'BE - REYES']);
        \DB::table('egp_ciudads')->insert(['id'=>'39', 'ciudad'=>'BE - RIBERALTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'41', 'ciudad'=>'BE - RURRENABAQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'379', 'ciudad'=>'BE - SAN ANDRES']);
        \DB::table('egp_ciudads')->insert(['id'=>'37', 'ciudad'=>'BE - SAN BORJA']);
        \DB::table('egp_ciudads')->insert(['id'=>'85', 'ciudad'=>'BE - SAN IGNACIO DE MOXOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'87', 'ciudad'=>'BE - SAN JAVIER']);
        \DB::table('egp_ciudads')->insert(['id'=>'89', 'ciudad'=>'BE - SAN JOAQUIN']);
        \DB::table('egp_ciudads')->insert(['id'=>'380', 'ciudad'=>'BE - SAN RAMON']);
        \DB::table('egp_ciudads')->insert(['id'=>'81', 'ciudad'=>'BE - SANTA ANA DEL YACUMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'79', 'ciudad'=>'BE - TRINIDAD']);
        \DB::table('egp_ciudads')->insert(['id'=>'168', 'ciudad'=>'CH - ALCALA']);
        \DB::table('egp_ciudads')->insert(['id'=>'120', 'ciudad'=>'CH - AZURDUY']);
        \DB::table('egp_ciudads')->insert(['id'=>'91', 'ciudad'=>'CH - CAMARGO']);
        \DB::table('egp_ciudads')->insert(['id'=>'65', 'ciudad'=>'CH - CHUQUISACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'173', 'ciudad'=>'CH - CULPINA']);
        \DB::table('egp_ciudads')->insert(['id'=>'169', 'ciudad'=>'CH - EL VILLAR']);
        \DB::table('egp_ciudads')->insert(['id'=>'132', 'ciudad'=>'CH - HUACARETA']);
        \DB::table('egp_ciudads')->insert(['id'=>'175', 'ciudad'=>'CH - HUACAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'166', 'ciudad'=>'CH - ICLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'172', 'ciudad'=>'CH - INCAHUASI']);
        \DB::table('egp_ciudads')->insert(['id'=>'174', 'ciudad'=>'CH - LAS CARRERAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'176', 'ciudad'=>'CH - MACHARETI']);
        \DB::table('egp_ciudads')->insert(['id'=>'165', 'ciudad'=>'CH - MOJOCOYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'2', 'ciudad'=>'CH - MONTEAGUDO']);
        \DB::table('egp_ciudads')->insert(['id'=>'167', 'ciudad'=>'CH - PADILLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'161', 'ciudad'=>'CH - POROMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'164', 'ciudad'=>'CH - PRESTO']);
        \DB::table('egp_ciudads')->insert(['id'=>'134', 'ciudad'=>'CH - SAN LUCAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'94', 'ciudad'=>'CH - SOPACHUY']);
        \DB::table('egp_ciudads')->insert(['id'=>'1', 'ciudad'=>'CH - SUCRE']);
        \DB::table('egp_ciudads')->insert(['id'=>'170', 'ciudad'=>'CH - TARABUCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'162', 'ciudad'=>'CH - TARVITA']);
        \DB::table('egp_ciudads')->insert(['id'=>'133', 'ciudad'=>'CH - TOMINA']);
        \DB::table('egp_ciudads')->insert(['id'=>'99', 'ciudad'=>'CH - VILLA ABECIA']);
        \DB::table('egp_ciudads')->insert(['id'=>'139', 'ciudad'=>'CH - VILLA CHARCAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'137', 'ciudad'=>'CH - VILLA SERRANO']);
        \DB::table('egp_ciudads')->insert(['id'=>'138', 'ciudad'=>'CH - VILLA VACA GUZMAN']);
        \DB::table('egp_ciudads')->insert(['id'=>'171', 'ciudad'=>'CH - YAMPARAEZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'141', 'ciudad'=>'CH - YOTALA']);
        \DB::table('egp_ciudads')->insert(['id'=>'163', 'ciudad'=>'CH - ZUDAÑEZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'13', 'ciudad'=>'CB - AIQUILE']);
        \DB::table('egp_ciudads')->insert(['id'=>'242', 'ciudad'=>'CB - ALALAY']);
        \DB::table('egp_ciudads')->insert(['id'=>'243', 'ciudad'=>'CB - ANZALDO']);
        \DB::table('egp_ciudads')->insert(['id'=>'72', 'ciudad'=>'CB - ARANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'244', 'ciudad'=>'CB - ARBIETO']);
        \DB::table('egp_ciudads')->insert(['id'=>'245', 'ciudad'=>'CB - ARQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'246', 'ciudad'=>'CB - AYOPAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'247', 'ciudad'=>'CB - BOLIVAR']);
        \DB::table('egp_ciudads')->insert(['id'=>'126', 'ciudad'=>'CB - CAPINOTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'97', 'ciudad'=>'CB - CERCADO']);
        \DB::table('egp_ciudads')->insert(['id'=>'248', 'ciudad'=>'CB - CHIMORE']);
        \DB::table('egp_ciudads')->insert(['id'=>'249', 'ciudad'=>'CB - CLIZA']);
        \DB::table('egp_ciudads')->insert(['id'=>'250', 'ciudad'=>'CB - COCAPATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'9', 'ciudad'=>'CB - COCHABAMBA']);
        \DB::table('egp_ciudads')->insert(['id'=>'159', 'ciudad'=>'CB - COLCAPIRHUA']);
        \DB::table('egp_ciudads')->insert(['id'=>'251', 'ciudad'=>'CB - COLOMI']);
        \DB::table('egp_ciudads')->insert(['id'=>'252', 'ciudad'=>'CB - CUCHUMUELA']);
        \DB::table('egp_ciudads')->insert(['id'=>'253', 'ciudad'=>'CB - ENTRE RIOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'112', 'ciudad'=>'CB - MANCOMUNIDAD DEL CONO SUR']);
        \DB::table('egp_ciudads')->insert(['id'=>'15', 'ciudad'=>'CB - MIZQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'254', 'ciudad'=>'CB - MOROCHATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'255', 'ciudad'=>'CB - OMEREQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'256', 'ciudad'=>'CB - PASARAPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'257', 'ciudad'=>'CB - POCONA']);
        \DB::table('egp_ciudads')->insert(['id'=>'258', 'ciudad'=>'CB - POJO']);
        \DB::table('egp_ciudads')->insert(['id'=>'259', 'ciudad'=>'CB - PUERTO VILLARROEL']);
        \DB::table('egp_ciudads')->insert(['id'=>'70', 'ciudad'=>'CB - PUNATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'10', 'ciudad'=>'CB - QUILLACOLLO']);
        \DB::table('egp_ciudads')->insert(['id'=>'11', 'ciudad'=>'CB - SACABA']);
        \DB::table('egp_ciudads')->insert(['id'=>'260', 'ciudad'=>'CB - SACABAMBA']);
        \DB::table('egp_ciudads')->insert(['id'=>'261', 'ciudad'=>'CB - SAN BENITO']);
        \DB::table('egp_ciudads')->insert(['id'=>'262', 'ciudad'=>'CB - SANTIVAÑEZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'74', 'ciudad'=>'CB - SHINAHOTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'263', 'ciudad'=>'CB - SICAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'71', 'ciudad'=>'CB - SIPE SIPE']);
        \DB::table('egp_ciudads')->insert(['id'=>'264', 'ciudad'=>'CB - TACACHI']);
        \DB::table('egp_ciudads')->insert(['id'=>'265', 'ciudad'=>'CB - TAPACARI']);
        \DB::table('egp_ciudads')->insert(['id'=>'266', 'ciudad'=>'CB - TARATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'157', 'ciudad'=>'CB - TIQUIPAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'267', 'ciudad'=>'CB - TIRAQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'268', 'ciudad'=>'CB - TOCOPAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'269', 'ciudad'=>'CB - TOKO']);
        \DB::table('egp_ciudads')->insert(['id'=>'270', 'ciudad'=>'CB - TOLATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'14', 'ciudad'=>'CB - TOTORA']);
        \DB::table('egp_ciudads')->insert(['id'=>'271', 'ciudad'=>'CB - VACAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'272', 'ciudad'=>'CB - VILA VILA']);
        \DB::table('egp_ciudads')->insert(['id'=>'273', 'ciudad'=>'CB - VILLA RIVERO']);
        \DB::table('egp_ciudads')->insert(['id'=>'12', 'ciudad'=>'CB - VILLA TUNARI']);
        \DB::table('egp_ciudads')->insert(['id'=>'160', 'ciudad'=>'CB - VINTO']);
        \DB::table('egp_ciudads')->insert(['id'=>'80', 'ciudad'=>'EX - EXTRANJERO']);
        \DB::table('egp_ciudads')->insert(['id'=>'7', 'ciudad'=>'LP - ACHACACHI']);
        \DB::table('egp_ciudads')->insert(['id'=>'177', 'ciudad'=>'LP - ACHOCALLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'178', 'ciudad'=>'LP - ALTO BENI']);
        \DB::table('egp_ciudads')->insert(['id'=>'179', 'ciudad'=>'LP - ANCORAIMES']);
        \DB::table('egp_ciudads')->insert(['id'=>'180', 'ciudad'=>'LP - APOLO']);
        \DB::table('egp_ciudads')->insert(['id'=>'181', 'ciudad'=>'LP - AUCAPATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'142', 'ciudad'=>'LP - AYATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'182', 'ciudad'=>'LP - AYO AYO']);
        \DB::table('egp_ciudads')->insert(['id'=>'183', 'ciudad'=>'LP - BATALLAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'184', 'ciudad'=>'LP - CAIROMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'185', 'ciudad'=>'LP - CAJUATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'186', 'ciudad'=>'LP - CALACOTO']);
        \DB::table('egp_ciudads')->insert(['id'=>'187', 'ciudad'=>'LP - CALAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'114', 'ciudad'=>'LP - CAQUIAVIRI']);
        \DB::table('egp_ciudads')->insert(['id'=>'5', 'ciudad'=>'LP - CARANAVI']);
        \DB::table('egp_ciudads')->insert(['id'=>'188', 'ciudad'=>'LP - CATACORA']);
        \DB::table('egp_ciudads')->insert(['id'=>'189', 'ciudad'=>'LP - CHARAÑA']);
        \DB::table('egp_ciudads')->insert(['id'=>'190', 'ciudad'=>'LP - CHARARILLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'191', 'ciudad'=>'LP - CHUA COCANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'96', 'ciudad'=>'LP - CHULUMANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'192', 'ciudad'=>'LP - CHUMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'194', 'ciudad'=>'LP - COLLANA']);
        \DB::table('egp_ciudads')->insert(['id'=>'193', 'ciudad'=>'LP - COLQUENCHA']);
        \DB::table('egp_ciudads')->insert(['id'=>'101', 'ciudad'=>'LP - COLQUIRI']);
        \DB::table('egp_ciudads')->insert(['id'=>'196', 'ciudad'=>'LP - COMANCHE']);
        \DB::table('egp_ciudads')->insert(['id'=>'195', 'ciudad'=>'LP - COMBAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'197', 'ciudad'=>'LP - COPACABANA']);
        \DB::table('egp_ciudads')->insert(['id'=>'198', 'ciudad'=>'LP - CORIPATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'123', 'ciudad'=>'LP - CORO CORO']);
        \DB::table('egp_ciudads')->insert(['id'=>'63', 'ciudad'=>'LP - COROICO']);
        \DB::table('egp_ciudads')->insert(['id'=>'124', 'ciudad'=>'LP - CURVA']);
        \DB::table('egp_ciudads')->insert(['id'=>'199', 'ciudad'=>'LP - DESAGUADERO']);
        \DB::table('egp_ciudads')->insert(['id'=>'4', 'ciudad'=>'LP - EL ALTO']);
        \DB::table('egp_ciudads')->insert(['id'=>'200', 'ciudad'=>'LP - ESCOMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'203', 'ciudad'=>'LP - GUANAY']);
        \DB::table('egp_ciudads')->insert(['id'=>'102', 'ciudad'=>'LP - GUAQUI']);
        \DB::table('egp_ciudads')->insert(['id'=>'201', 'ciudad'=>'LP - HUARINA']);
        \DB::table('egp_ciudads')->insert(['id'=>'204', 'ciudad'=>'LP - HUATAJATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'202', 'ciudad'=>'LP - HUMANATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'205', 'ciudad'=>'LP - ICHOCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'206', 'ciudad'=>'LP - INQUISIVI']);
        \DB::table('egp_ciudads')->insert(['id'=>'207', 'ciudad'=>'LP - IRUPANA']);
        \DB::table('egp_ciudads')->insert(['id'=>'208', 'ciudad'=>'LP - IXIAMAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'144', 'ciudad'=>'LP - JESUS DE MACHACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'125', 'ciudad'=>'LP - JUAN JOSE PEREZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'209', 'ciudad'=>'LP - LA ASUNTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'210', 'ciudad'=>'LP - LAJA']);
        \DB::table('egp_ciudads')->insert(['id'=>'3', 'ciudad'=>'LP - LA PAZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'155', 'ciudad'=>'LP - LICOMA PAMPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'211', 'ciudad'=>'LP - LURIBAY']);
        \DB::table('egp_ciudads')->insert(['id'=>'212', 'ciudad'=>'LP - MALLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'213', 'ciudad'=>'LP - MAPIRI']);
        \DB::table('egp_ciudads')->insert(['id'=>'214', 'ciudad'=>'LP - MECAPACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'215', 'ciudad'=>'LP - MOCOMOCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'143', 'ciudad'=>'LP - NAZACARA DE PACAJES']);
        \DB::table('egp_ciudads')->insert(['id'=>'216', 'ciudad'=>'LP - PALCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'121', 'ciudad'=>'LP - PALOS BLANCOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'217', 'ciudad'=>'LP - PAPEL PAMPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'8', 'ciudad'=>'LP - PATACAMAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'218', 'ciudad'=>'LP - PELECHUCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'219', 'ciudad'=>'LP - PUCARANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'220', 'ciudad'=>'LP - PUERTO ACOSTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'221', 'ciudad'=>'LP - PUERTO CARABUCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'222', 'ciudad'=>'LP - PUERTO PEREZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'231', 'ciudad'=>'LP - QUIABAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'232', 'ciudad'=>'LP - QUIME']);
        \DB::table('egp_ciudads')->insert(['id'=>'226', 'ciudad'=>'LP - SAN ANDRES DE MACHACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'6', 'ciudad'=>'LP - SAN BUENA VENTURA']);
        \DB::table('egp_ciudads')->insert(['id'=>'227', 'ciudad'=>'LP - SAN PEDRO DE CURAHUARA']);
        \DB::table('egp_ciudads')->insert(['id'=>'228', 'ciudad'=>'LP - SAN PEDRO DE TIQUINA']);
        \DB::table('egp_ciudads')->insert(['id'=>'223', 'ciudad'=>'LP - SANTIAGO DE CALLAPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'224', 'ciudad'=>'LP - SANTIAGO DE HUATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'225', 'ciudad'=>'LP - SANTIAGO DE MACHACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'229', 'ciudad'=>'LP - SAPAHAQUI']);
        \DB::table('egp_ciudads')->insert(['id'=>'230', 'ciudad'=>'LP - SICA SICA']);
        \DB::table('egp_ciudads')->insert(['id'=>'116', 'ciudad'=>'LP - SORATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'233', 'ciudad'=>'LP - TACACOMA']);
        \DB::table('egp_ciudads')->insert(['id'=>'234', 'ciudad'=>'LP - TARACO']);
        \DB::table('egp_ciudads')->insert(['id'=>'235', 'ciudad'=>'LP - TEOPONTE']);
        \DB::table('egp_ciudads')->insert(['id'=>'147', 'ciudad'=>'LP - TIAWANACU']);
        \DB::table('egp_ciudads')->insert(['id'=>'236', 'ciudad'=>'LP - TIPUANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'237', 'ciudad'=>'LP - TITO YUPANQUI']);
        \DB::table('egp_ciudads')->insert(['id'=>'238', 'ciudad'=>'LP - UMALA']);
        \DB::table('egp_ciudads')->insert(['id'=>'66', 'ciudad'=>'LP - VIACHA']);
        \DB::table('egp_ciudads')->insert(['id'=>'239', 'ciudad'=>'LP - WALDO BALLIVIAN']);
        \DB::table('egp_ciudads')->insert(['id'=>'240', 'ciudad'=>'LP - YACO']);
        \DB::table('egp_ciudads')->insert(['id'=>'241', 'ciudad'=>'LP - YANACACHI']);
        \DB::table('egp_ciudads')->insert(['id'=>'274', 'ciudad'=>'OR - ANDAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'275', 'ciudad'=>'OR - ANTEQUERA']);
        \DB::table('egp_ciudads')->insert(['id'=>'276', 'ciudad'=>'OR - BELEN DE ANDAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'17', 'ciudad'=>'OR - CARACOLLO']);
        \DB::table('egp_ciudads')->insert(['id'=>'131', 'ciudad'=>'OR - CHALLAPATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'277', 'ciudad'=>'OR - CHIPAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'278', 'ciudad'=>'OR - CHOQUECOTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'279', 'ciudad'=>'OR - COIPASA']);
        \DB::table('egp_ciudads')->insert(['id'=>'280', 'ciudad'=>'OR - CORQUE']);
        \DB::table('egp_ciudads')->insert(['id'=>'281', 'ciudad'=>'OR - CRUZ DE MACHACAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'282', 'ciudad'=>'OR - CURAHUARA DE CARANGAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'283', 'ciudad'=>'OR - EL CHORRO']);
        \DB::table('egp_ciudads')->insert(['id'=>'284', 'ciudad'=>'OR - ESCARA']);
        \DB::table('egp_ciudads')->insert(['id'=>'285', 'ciudad'=>'OR - ESMERALDA']);
        \DB::table('egp_ciudads')->insert(['id'=>'286', 'ciudad'=>'OR - EUCALIPTUS']);
        \DB::table('egp_ciudads')->insert(['id'=>'287', 'ciudad'=>'OR - HUACHACALLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'69', 'ciudad'=>'OR - HUANUNI']);
        \DB::table('egp_ciudads')->insert(['id'=>'288', 'ciudad'=>'OR - HUAYLLAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'289', 'ciudad'=>'OR - LA RIVERA']);
        \DB::table('egp_ciudads')->insert(['id'=>'290', 'ciudad'=>'OR - MACHACAMARCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'16', 'ciudad'=>'OR - ORURO']);
        \DB::table('egp_ciudads')->insert(['id'=>'291', 'ciudad'=>'OR - PAMPA AULLAGAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'292', 'ciudad'=>'OR - PARI O SORACACHI']);
        \DB::table('egp_ciudads')->insert(['id'=>'293', 'ciudad'=>'OR - PAZÑA']);
        \DB::table('egp_ciudads')->insert(['id'=>'68', 'ciudad'=>'OR - POOPO']);
        \DB::table('egp_ciudads')->insert(['id'=>'294', 'ciudad'=>'OR - QUILLACAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'295', 'ciudad'=>'OR - SABAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'296', 'ciudad'=>'OR - SALINAS DE GARCI MENDOZA']);
        \DB::table('egp_ciudads')->insert(['id'=>'130', 'ciudad'=>'OR - SANTIAGO DE HUARI']);
        \DB::table('egp_ciudads')->insert(['id'=>'297', 'ciudad'=>'OR - TODOS SANTOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'298', 'ciudad'=>'OR - TOLEDO']);
        \DB::table('egp_ciudads')->insert(['id'=>'299', 'ciudad'=>'OR - TOTORA']);
        \DB::table('egp_ciudads')->insert(['id'=>'300', 'ciudad'=>'OR - TURCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'301', 'ciudad'=>'OR - YUNGUYO DEL LITORAL']);
        \DB::table('egp_ciudads')->insert(['id'=>'64', 'ciudad'=>'OT - NACIONAL']);
        \DB::table('egp_ciudads')->insert(['id'=>'393', 'ciudad'=>'OT - OTROS']);
        \DB::table('egp_ciudads')->insert(['id'=>'394', 'ciudad'=>'OT - SIN DEFINIR']);
        \DB::table('egp_ciudads')->insert(['id'=>'383', 'ciudad'=>'PA - BELLA FLOR']);
        \DB::table('egp_ciudads')->insert(['id'=>'382', 'ciudad'=>'PA - BOLPEBRA']);
        \DB::table('egp_ciudads')->insert(['id'=>'42', 'ciudad'=>'PA - COBIJA']);
        \DB::table('egp_ciudads')->insert(['id'=>'387', 'ciudad'=>'PA - EL SENA']);
        \DB::table('egp_ciudads')->insert(['id'=>'385', 'ciudad'=>'PA - FILADELFIA']);
        \DB::table('egp_ciudads')->insert(['id'=>'389', 'ciudad'=>'PA - INGAVI']);
        \DB::table('egp_ciudads')->insert(['id'=>'390', 'ciudad'=>'PA - NUEVA ESPERANZA']);
        \DB::table('egp_ciudads')->insert(['id'=>'381', 'ciudad'=>'PA - PORVENIR']);
        \DB::table('egp_ciudads')->insert(['id'=>'43', 'ciudad'=>'PA - PUERTO GONZALO MORENO']);
        \DB::table('egp_ciudads')->insert(['id'=>'44', 'ciudad'=>'PA - PUERTO RICO']);
        \DB::table('egp_ciudads')->insert(['id'=>'386', 'ciudad'=>'PA - SAN LORENZO']);
        \DB::table('egp_ciudads')->insert(['id'=>'384', 'ciudad'=>'PA - SAN PEDRO']);
        \DB::table('egp_ciudads')->insert(['id'=>'388', 'ciudad'=>'PA - SANTA ROSA DEL ABUNÁ']);
        \DB::table('egp_ciudads')->insert(['id'=>'392', 'ciudad'=>'PA - SANTOS MERCADO']);
        \DB::table('egp_ciudads')->insert(['id'=>'391', 'ciudad'=>'PA - VILLA NUEVA']);
        \DB::table('egp_ciudads')->insert(['id'=>'302', 'ciudad'=>'PO - ACASIO']);
        \DB::table('egp_ciudads')->insert(['id'=>'303', 'ciudad'=>'PO - ARAMPAMPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'108', 'ciudad'=>'PO - ATOCHA']);
        \DB::table('egp_ciudads')->insert(['id'=>'153', 'ciudad'=>'PO - BETANZOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'140', 'ciudad'=>'PO - CAIZA "D"']);
        \DB::table('egp_ciudads')->insert(['id'=>'304', 'ciudad'=>'PO - CARIPUYO']);
        \DB::table('egp_ciudads')->insert(['id'=>'305', 'ciudad'=>'PO - CHAQUI']);
        \DB::table('egp_ciudads')->insert(['id'=>'92', 'ciudad'=>'PO - CHAYANTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'306', 'ciudad'=>'PO - CHUQUIHUTA AYLLU JUCUMANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'307', 'ciudad'=>'PO - CKOCHAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'308', 'ciudad'=>'PO - COLCHA K']);
        \DB::table('egp_ciudads')->insert(['id'=>'309', 'ciudad'=>'PO - COLQUECHACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'104', 'ciudad'=>'PO - COTAGAITA']);
        \DB::table('egp_ciudads')->insert(['id'=>'20', 'ciudad'=>'PO - LLALLAGUA']);
        \DB::table('egp_ciudads')->insert(['id'=>'310', 'ciudad'=>'PO - LLICA']);
        \DB::table('egp_ciudads')->insert(['id'=>'311', 'ciudad'=>'PO - MOJINETE']);
        \DB::table('egp_ciudads')->insert(['id'=>'312', 'ciudad'=>'PO - OCURI']);
        \DB::table('egp_ciudads')->insert(['id'=>'146', 'ciudad'=>'PO - POCOATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'127', 'ciudad'=>'PO - POCOATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'313', 'ciudad'=>'PO - PORCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'18', 'ciudad'=>'PO - POTOSI']);
        \DB::table('egp_ciudads')->insert(['id'=>'90', 'ciudad'=>'PO - PUNA']);
        \DB::table('egp_ciudads')->insert(['id'=>'314', 'ciudad'=>'PO - RAVELO']);
        \DB::table('egp_ciudads')->insert(['id'=>'315', 'ciudad'=>'PO - SACACA']);
        \DB::table('egp_ciudads')->insert(['id'=>'316', 'ciudad'=>'PO - SAN AGUSTIN']);
        \DB::table('egp_ciudads')->insert(['id'=>'317', 'ciudad'=>'PO - SAN ANTONIO DE ESMORUCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'95', 'ciudad'=>'PO - SAN PABLO']);
        \DB::table('egp_ciudads')->insert(['id'=>'318', 'ciudad'=>'PO - SAN PEDRO']);
        \DB::table('egp_ciudads')->insert(['id'=>'319', 'ciudad'=>'PO - SAN PEDRO DE QUEMES']);
        \DB::table('egp_ciudads')->insert(['id'=>'320', 'ciudad'=>'PO - TACOBAMBA']);
        \DB::table('egp_ciudads')->insert(['id'=>'321', 'ciudad'=>'PO - TAHUA']);
        \DB::table('egp_ciudads')->insert(['id'=>'322', 'ciudad'=>'PO - TINGUIPAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'323', 'ciudad'=>'PO - TOMAVE']);
        \DB::table('egp_ciudads')->insert(['id'=>'324', 'ciudad'=>'PO - TORO TORO']);
        \DB::table('egp_ciudads')->insert(['id'=>'62', 'ciudad'=>'PO - TUPIZA']);
        \DB::table('egp_ciudads')->insert(['id'=>'22', 'ciudad'=>'PO - UNCIA']);
        \DB::table('egp_ciudads')->insert(['id'=>'122', 'ciudad'=>'PO - URMIRI']);
        \DB::table('egp_ciudads')->insert(['id'=>'19', 'ciudad'=>'PO - UYUNI']);
        \DB::table('egp_ciudads')->insert(['id'=>'23', 'ciudad'=>'PO - VILLAZON']);
        \DB::table('egp_ciudads')->insert(['id'=>'325', 'ciudad'=>'PO - VITICHI']);
        \DB::table('egp_ciudads')->insert(['id'=>'326', 'ciudad'=>'PO - YOCALLA']);
        \DB::table('egp_ciudads')->insert(['id'=>'32', 'ciudad'=>'SC - ASCENSION DE GUARAYOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'331', 'ciudad'=>'SC - AYACUCHO']);
        \DB::table('egp_ciudads')->insert(['id'=>'332', 'ciudad'=>'SC - BOYUIBE']);
        \DB::table('egp_ciudads')->insert(['id'=>'333', 'ciudad'=>'SC - BUENA VISTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'334', 'ciudad'=>'SC - CABEZAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'34', 'ciudad'=>'SC - CAMIRI']);
        \DB::table('egp_ciudads')->insert(['id'=>'335', 'ciudad'=>'SC - CARMEN RIVERO TORREZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'336', 'ciudad'=>'SC - CHARAGUA']);
        \DB::table('egp_ciudads')->insert(['id'=>'337', 'ciudad'=>'SC - COLPA BELGICA']);
        \DB::table('egp_ciudads')->insert(['id'=>'338', 'ciudad'=>'SC - COMARAPA']);
        \DB::table('egp_ciudads')->insert(['id'=>'339', 'ciudad'=>'SC - CONCEPCION']);
        \DB::table('egp_ciudads')->insert(['id'=>'340', 'ciudad'=>'SC - COTOCA']);
        \DB::table('egp_ciudads')->insert(['id'=>'341', 'ciudad'=>'SC - CUATRO CAÑADAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'342', 'ciudad'=>'SC - CUEVO']);
        \DB::table('egp_ciudads')->insert(['id'=>'343', 'ciudad'=>'SC - EL PUENTE']);
        \DB::table('egp_ciudads')->insert(['id'=>'344', 'ciudad'=>'SC - EL TORNO']);
        \DB::table('egp_ciudads')->insert(['id'=>'345', 'ciudad'=>'SC - FERNANDEZ ALONSO']);
        \DB::table('egp_ciudads')->insert(['id'=>'346', 'ciudad'=>'SC - GENERAL SAAVEDRA']);
        \DB::table('egp_ciudads')->insert(['id'=>'347', 'ciudad'=>'SC - GUTIERREZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'156', 'ciudad'=>'SC - LA GUARDIA']);
        \DB::table('egp_ciudads')->insert(['id'=>'348', 'ciudad'=>'SC - LAGUNILLAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'349', 'ciudad'=>'SC - MAIRANA']);
        \DB::table('egp_ciudads')->insert(['id'=>'350', 'ciudad'=>'SC - MINEROS']);
        \DB::table('egp_ciudads')->insert(['id'=>'30', 'ciudad'=>'SC - MONTERO']);
        \DB::table('egp_ciudads')->insert(['id'=>'351', 'ciudad'=>'SC - MORO MORO']);
        \DB::table('egp_ciudads')->insert(['id'=>'352', 'ciudad'=>'SC - OKINAWA I']);
        \DB::table('egp_ciudads')->insert(['id'=>'353', 'ciudad'=>'SC - PAILON']);
        \DB::table('egp_ciudads')->insert(['id'=>'354', 'ciudad'=>'SC - PAMPA GRANDE']);
        \DB::table('egp_ciudads')->insert(['id'=>'93', 'ciudad'=>'SC - PORTACHUELO']);
        \DB::table('egp_ciudads')->insert(['id'=>'355', 'ciudad'=>'SC - POSTRER VALLE']);
        \DB::table('egp_ciudads')->insert(['id'=>'356', 'ciudad'=>'SC - PUCARA']);
        \DB::table('egp_ciudads')->insert(['id'=>'357', 'ciudad'=>'SC - PUERTO QUIJARRO']);
        \DB::table('egp_ciudads')->insert(['id'=>'33', 'ciudad'=>'SC - PUERTO SUAREZ']);
        \DB::table('egp_ciudads')->insert(['id'=>'358', 'ciudad'=>'SC - QUIRUSILLAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'359', 'ciudad'=>'SC - ROBORE']);
        \DB::table('egp_ciudads')->insert(['id'=>'360', 'ciudad'=>'SC - SAIPINA']);
        \DB::table('egp_ciudads')->insert(['id'=>'361', 'ciudad'=>'SC - SAMAIPATA']);
        \DB::table('egp_ciudads')->insert(['id'=>'362', 'ciudad'=>'SC - SAN ANTONIO DE LOMERIO']);
        \DB::table('egp_ciudads')->insert(['id'=>'363', 'ciudad'=>'SC - SAN CARLOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'158', 'ciudad'=>'SC - SAN IGNACIO DE VELASCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'364', 'ciudad'=>'SC - SAN JAVIER']);
        \DB::table('egp_ciudads')->insert(['id'=>'365', 'ciudad'=>'SC - SAN JOSE DE CHIQUITOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'366', 'ciudad'=>'SC - SAN JUAN']);
        \DB::table('egp_ciudads')->insert(['id'=>'367', 'ciudad'=>'SC - SAN JULIAN']);
        \DB::table('egp_ciudads')->insert(['id'=>'368', 'ciudad'=>'SC - SAN MATIAS']);
        \DB::table('egp_ciudads')->insert(['id'=>'369', 'ciudad'=>'SC - SAN MIGUEL']);
        \DB::table('egp_ciudads')->insert(['id'=>'370', 'ciudad'=>'SC - SAN PEDRO DE BUENA VISTA']);
        \DB::table('egp_ciudads')->insert(['id'=>'371', 'ciudad'=>'SC - SAN RAFAEL DE VELASCO']);
        \DB::table('egp_ciudads')->insert(['id'=>'372', 'ciudad'=>'SC - SAN RAMON']);
        \DB::table('egp_ciudads')->insert(['id'=>'29', 'ciudad'=>'SC - SANTA CRUZ DE LA SIERRA']);
        \DB::table('egp_ciudads')->insert(['id'=>'373', 'ciudad'=>'SC - SANTA ROSA DEL SARA']);
        \DB::table('egp_ciudads')->insert(['id'=>'374', 'ciudad'=>'SC - TRIGAL']);
        \DB::table('egp_ciudads')->insert(['id'=>'375', 'ciudad'=>'SC - URUBICHA']);
        \DB::table('egp_ciudads')->insert(['id'=>'107', 'ciudad'=>'SC - VALLEGRANDE']);
        \DB::table('egp_ciudads')->insert(['id'=>'31', 'ciudad'=>'SC - WARNES']);
        \DB::table('egp_ciudads')->insert(['id'=>'35', 'ciudad'=>'SC - YAPACANI']);
        \DB::table('egp_ciudads')->insert(['id'=>'26', 'ciudad'=>'TJ - BERMEJO']);
        \DB::table('egp_ciudads')->insert(['id'=>'328', 'ciudad'=>'TJ - CARAPARI']);
        \DB::table('egp_ciudads')->insert(['id'=>'119', 'ciudad'=>'TJ - EL PUENTE']);
        \DB::table('egp_ciudads')->insert(['id'=>'28', 'ciudad'=>'TJ - ENTRE RIOS']);
        \DB::table('egp_ciudads')->insert(['id'=>'327', 'ciudad'=>'TJ - PADCAYA']);
        \DB::table('egp_ciudads')->insert(['id'=>'73', 'ciudad'=>'TJ - SAN LORENZO']);
        \DB::table('egp_ciudads')->insert(['id'=>'24', 'ciudad'=>'TJ - TARIJA']);
        \DB::table('egp_ciudads')->insert(['id'=>'329', 'ciudad'=>'TJ - URIONDO']);
        \DB::table('egp_ciudads')->insert(['id'=>'27', 'ciudad'=>'TJ - VILLAMONTES']);
        \DB::table('egp_ciudads')->insert(['id'=>'25', 'ciudad'=>'TJ - YACUIBA']);
        \DB::table('egp_ciudads')->insert(['id'=>'330', 'ciudad'=>'TJ - YUNCHARA']);

        \DB::table('egp_nacimientos')->insert(['id'=>'1', 'nacimiento'=>'CHUQUISACA']);
        \DB::table('egp_nacimientos')->insert(['id'=>'3', 'nacimiento'=>'LA PAZ']);
        \DB::table('egp_nacimientos')->insert(['id'=>'9', 'nacimiento'=>'COCHABAMBA']);
        \DB::table('egp_nacimientos')->insert(['id'=>'16', 'nacimiento'=>'ORURO']);
        \DB::table('egp_nacimientos')->insert(['id'=>'18', 'nacimiento'=>'POTOSI']);
        \DB::table('egp_nacimientos')->insert(['id'=>'24', 'nacimiento'=>'TARIJA']);
        \DB::table('egp_nacimientos')->insert(['id'=>'29', 'nacimiento'=>'SANTA CRUZ']);
        \DB::table('egp_nacimientos')->insert(['id'=>'36', 'nacimiento'=>'BENI']);
        \DB::table('egp_nacimientos')->insert(['id'=>'42', 'nacimiento'=>'PANDO']);
        \DB::table('egp_nacimientos')->insert(['id'=>'80', 'nacimiento'=>'>EXTRANJERO']);


        \DB::table('egp_profesions')->insert(['id'=>'125', 'profesion'=>'ACRIMENSURA']);
        \DB::table('egp_profesions')->insert(['id'=>'39', 'profesion'=>'AGRICULTOR (YAPUCHIRI)']);
        \DB::table('egp_profesions')->insert(['id'=>'67', 'profesion'=>'DISEÑADOR GRÁFICO']);
        \DB::table('egp_profesions')->insert(['id'=>'0', 'profesion'=>'ESTUDIANTE']);
        \DB::table('egp_profesions')->insert(['id'=>'95', 'profesion'=>'FUNCIONARIO DEL BANCO']);
        \DB::table('egp_profesions')->insert(['id'=>'115', 'profesion'=>'GASTRÓNOMO']);
        \DB::table('egp_profesions')->insert(['id'=>'32', 'profesion'=>'INDEPENDIENTE']);
        \DB::table('egp_profesions')->insert(['id'=>'124', 'profesion'=>'ING. FINANCIERA/O']);
        \DB::table('egp_profesions')->insert(['id'=>'22', 'profesion'=>'ING. FORESTAL']);
        \DB::table('egp_profesions')->insert(['id'=>'49', 'profesion'=>'ING./LIC./TS AERONAUTICO']);
        \DB::table('egp_profesions')->insert(['id'=>'21', 'profesion'=>'ING./LIC./TS AGRÓNOMO']);
        \DB::table('egp_profesions')->insert(['id'=>'20', 'profesion'=>'ING./LIC./TS ALIMENTOS']);
        \DB::table('egp_profesions')->insert(['id'=>'114', 'profesion'=>'ING./LIC/TS AMBIENTAL']);
        \DB::table('egp_profesions')->insert(['id'=>'112', 'profesion'=>'ING./LIC./TS AUTOMOTRIZ']);
        \DB::table('egp_profesions')->insert(['id'=>'19', 'profesion'=>'ING./LIC./TS COMERCIAL']);
        \DB::table('egp_profesions')->insert(['id'=>'6', 'profesion'=>'ING./LIC./TS CONSTRUCCIÓN CIVIL']);
        \DB::table('egp_profesions')->insert(['id'=>'113', 'profesion'=>'ING./LIC./TS ELÉCTRICO']);
        \DB::table('egp_profesions')->insert(['id'=>'83', 'profesion'=>'ING./LIC./TS ELECTROMECÁNICO']);
        \DB::table('egp_profesions')->insert(['id'=>'5', 'profesion'=>'ING./LIC./TS ELECTRÓNICA']);
        \DB::table('egp_profesions')->insert(['id'=>'16', 'profesion'=>'ING./LIC./TS FÍSICO']);
        \DB::table('egp_profesions')->insert(['id'=>'77', 'profesion'=>'ING./LIC./TS INDUSTRIAL']);
        \DB::table('egp_profesions')->insert(['id'=>'110', 'profesion'=>'ING./LIC./TS MARKETING']);
        \DB::table('egp_profesions')->insert(['id'=>'43', 'profesion'=>'ING./LIC./TS MECÁNICO']);
        \DB::table('egp_profesions')->insert(['id'=>'80', 'profesion'=>'ING./LIC./TS METALURGIA']);
        \DB::table('egp_profesions')->insert(['id'=>'27', 'profesion'=>'ING./LIC./TS PETROLERO']);
        \DB::table('egp_profesions')->insert(['id'=>'116', 'profesion'=>'ING./LIC./TS PRODUCCIÓN']);
        \DB::table('egp_profesions')->insert(['id'=>'17', 'profesion'=>'ING./LIC./TS QUÍMICO']);
        \DB::table('egp_profesions')->insert(['id'=>'7', 'profesion'=>'ING./LIC./TS SISTEMAS INFORMÁTICOS']);
        \DB::table('egp_profesions')->insert(['id'=>'117', 'profesion'=>'ING./LIC./TS SONIDO']);
        \DB::table('egp_profesions')->insert(['id'=>'9', 'profesion'=>'ING./LIC./TS TELECOMUNICACIONES']);
        \DB::table('egp_profesions')->insert(['id'=>'88', 'profesion'=>'ING./LIC./TS TOPÓGRAFO']);
        \DB::table('egp_profesions')->insert(['id'=>'30', 'profesion'=>'ING. TECNOLOGIA ESPACIAL']);
        \DB::table('egp_profesions')->insert(['id'=>'4', 'profesion'=>'LIC. ADMINISTRACION DE EMPRESAS']);
        \DB::table('egp_profesions')->insert(['id'=>'62', 'profesion'=>'LIC. ANTROPOLOGÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'14', 'profesion'=>'LIC. ARQUITECTURA']);
        \DB::table('egp_profesions')->insert(['id'=>'1', 'profesion'=>'LIC. AUDITORIA']);
        \DB::table('egp_profesions')->insert(['id'=>'85', 'profesion'=>'LIC. BIBLIOTECOLOGÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'74', 'profesion'=>'LIC. BIOQUÍMICA']);
        \DB::table('egp_profesions')->insert(['id'=>'18', 'profesion'=>'LIC. CIENCIAS DE LA EDUCACION']);
        \DB::table('egp_profesions')->insert(['id'=>'111', 'profesion'=>'LIC. CIENCIAS SOCIALES']);
        \DB::table('egp_profesions')->insert(['id'=>'118', 'profesion'=>'LIC. COMERCIO EXTERIOR']);
        \DB::table('egp_profesions')->insert(['id'=>'52', 'profesion'=>'LIC. COMUNICACIÓN SOCIAL']);
        \DB::table('egp_profesions')->insert(['id'=>'2', 'profesion'=>'LIC. DERECHO']);
        \DB::table('egp_profesions')->insert(['id'=>'3', 'profesion'=>'LIC. ECONOMÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'75', 'profesion'=>'LIC. EN LABORATORIO CLÍNICO']);
        \DB::table('egp_profesions')->insert(['id'=>'15', 'profesion'=>'LIC. ESTADISTICA']);
        \DB::table('egp_profesions')->insert(['id'=>'96', 'profesion'=>'LIC. IDIOMAS']);
        \DB::table('egp_profesions')->insert(['id'=>'10', 'profesion'=>'LIC. MEDICINA']);
        \DB::table('egp_profesions')->insert(['id'=>'119', 'profesion'=>'LIC. MERCADOTECNIA']);
        \DB::table('egp_profesions')->insert(['id'=>'120', 'profesion'=>'LIC. NUTRICIÓN']);
        \DB::table('egp_profesions')->insert(['id'=>'121', 'profesion'=>'LIC. PARVULARIA']);
        \DB::table('egp_profesions')->insert(['id'=>'65', 'profesion'=>'LIC. PEDAGOGÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'56', 'profesion'=>'LIC. POLITOLOGO']);
        \DB::table('egp_profesions')->insert(['id'=>'55', 'profesion'=>'LIC. PSICOLOGIA']);
        \DB::table('egp_profesions')->insert(['id'=>'123', 'profesion'=>'LIC. RELACIONES INTERNACIONALES']);
        \DB::table('egp_profesions')->insert(['id'=>'76', 'profesion'=>'LIC. SOCIOLOGÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'71', 'profesion'=>'LIC. TRABAJO SOCIAL']);
        \DB::table('egp_profesions')->insert(['id'=>'109', 'profesion'=>'LIC./TS BIOLOGÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'13', 'profesion'=>'LIC./TS CONTADURÍA PÚBLICA']);
        \DB::table('egp_profesions')->insert(['id'=>'11', 'profesion'=>'LIC./TS ENFERMERÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'12', 'profesion'=>'LIC./TS ODONTOLOGIA']);
        \DB::table('egp_profesions')->insert(['id'=>'97', 'profesion'=>'LIC. TURISMO &amp; HOTELERÍA']);
        \DB::table('egp_profesions')->insert(['id'=>'23', 'profesion'=>'LIC. VETERINARIA']);
        \DB::table('egp_profesions')->insert(['id'=>'45', 'profesion'=>'METEREOLOGO']);
        \DB::table('egp_profesions')->insert(['id'=>'61', 'profesion'=>'MILITAR']);
        \DB::table('egp_profesions')->insert(['id'=>'36', 'profesion'=>'OTROS']);
        \DB::table('egp_profesions')->insert(['id'=>'48', 'profesion'=>'PILOTO DE AVIACIÓN']);
        \DB::table('egp_profesions')->insert(['id'=>'24', 'profesion'=>'PROFESOR']);
        \DB::table('egp_profesions')->insert(['id'=>'68', 'profesion'=>'RECEPCIONISTA']);
        \DB::table('egp_profesions')->insert(['id'=>'31', 'profesion'=>'SECRETARIA']);
        \DB::table('egp_profesions')->insert(['id'=>'34', 'profesion'=>'SERVIDOR/A PÚBLICO']);
        \DB::table('egp_profesions')->insert(['id'=>'122', 'profesion'=>'SIN DEFINIR']);




        \DB::table('egp_empresas')->insert(['id'=>'48', 'empresa'=>'ADMINISTRACIÓN BOLIVIANA DE CARRETERAS']);
        \DB::table('egp_empresas')->insert(['id'=>'163', 'empresa'=>'ADMINISTRACIÓN DE AEROPUERTOS Y SERVICIOS AUXILIARES A LA NAVEGACIÓN AÉREA - AASANA']);
        \DB::table('egp_empresas')->insert(['id'=>'228', 'empresa'=>'ADMINISTRACIÓN DE SERVICIOS PORTUARIOS BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'137', 'empresa'=>'ADUANA NACIONAL DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'408', 'empresa'=>'AGENCIA BOLIVIANA DE ENERGÍA NUCLEAR']);
        \DB::table('egp_empresas')->insert(['id'=>'393', 'empresa'=>'AGENCIA BOLIVIANA ESPACIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'405', 'empresa'=>'AGENCIA DE GOBIERNO ELECTRÓNICO Y TECNOLOGÍAS DE INFORMACIÓN Y COMUNICACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'407', 'empresa'=>'AGENCIA DE INFRAESTRUCTURA EN SALUD Y EQUIPAMIENTO MÉDICO']);
        \DB::table('egp_empresas')->insert(['id'=>'91', 'empresa'=>'AGENCIA ESTATAL DE VIVIENDA']);
        \DB::table('egp_empresas')->insert(['id'=>'17', 'empresa'=>'AGENCIA NACIONAL DE HIDROCARBUROS']);
        \DB::table('egp_empresas')->insert(['id'=>'166', 'empresa'=>'AGENCIA PARA EL DESARROLLO DE LAS MACRO REGIONES Y ZONAS FRONTERIZAS - ADEMAF']);
        \DB::table('egp_empresas')->insert(['id'=>'9', 'empresa'=>'AGENCIA PARA EL DESARROLLO DE LA SOCIEDAD DE LA INFORMACION EN BOLIVIA - ADSIB']);
        \DB::table('egp_empresas')->insert(['id'=>'399', 'empresa'=>'ARMADA BOLIVIANA']);
        \DB::table('egp_empresas')->insert(['id'=>'196', 'empresa'=>'ASOCIACIÓN BOLIVIANA DE MEDICINA']);
        \DB::table('egp_empresas')->insert(['id'=>'254', 'empresa'=>'ASOCIACIONES DE AGENTES DE VALORES']);
        \DB::table('egp_empresas')->insert(['id'=>'255', 'empresa'=>'ASOCIACIONES DE AGRICULTORES']);
        \DB::table('egp_empresas')->insert(['id'=>'256', 'empresa'=>'ASOCIACIONES DE ASEGURADORES']);
        \DB::table('egp_empresas')->insert(['id'=>'257', 'empresa'=>'ASOCIACIONES DE BANCOS PRIVADOS']);
        \DB::table('egp_empresas')->insert(['id'=>'258', 'empresa'=>'ASOCIACIONES DE CAÑEROS']);
        \DB::table('egp_empresas')->insert(['id'=>'259', 'empresa'=>'ASOCIACIONES DE INGENIOS MINEROS']);
        \DB::table('egp_empresas')->insert(['id'=>'260', 'empresa'=>'ASOCIACIONES DE INSTITUTOS, ACADEMIAS Y ESCUELAS DE PROFESIONALIZACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'261', 'empresa'=>'ASOCIACIONES DE MINEROS MEDIANOS']);
        \DB::table('egp_empresas')->insert(['id'=>'262', 'empresa'=>'ASOCIACIONES DE MUNICIPIOS']);
        \DB::table('egp_empresas')->insert(['id'=>'263', 'empresa'=>'ASOCIACIONES DE PERIODISTAS']);
        \DB::table('egp_empresas')->insert(['id'=>'264', 'empresa'=>'ASOCIACIONES DE TRABAJADORES DE CARNE VACUNA']);
        \DB::table('egp_empresas')->insert(['id'=>'265', 'empresa'=>'ASOCIACIONES FINANCIERAS']);
        \DB::table('egp_empresas')->insert(['id'=>'266', 'empresa'=>'ASOCIACIONES RECAUDADORA DE DERECHO Y EJECUCIÓN PÚBLICA']);
        \DB::table('egp_empresas')->insert(['id'=>'267', 'empresa'=>'ASOCIACIONES SOCIALES Y CIVICAS']);
        \DB::table('egp_empresas')->insert(['id'=>'172', 'empresa'=>'ASOCIACIÓN ÑANDE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'55', 'empresa'=>'AUTORIDAD BINACIONAL DEL LAGO TITICACA']);
        \DB::table('egp_empresas')->insert(['id'=>'67', 'empresa'=>'AUTORIDAD DE FISCALIZACIóN Y CONTROL DE PENSIONES Y SEGURO']);
        \DB::table('egp_empresas')->insert(['id'=>'229', 'empresa'=>'AUTORIDAD DE FISCALIZACIÓN Y CONTROL SOCIAL DE AGUA POTABLE Y SANEAMIENTO']);
        \DB::table('egp_empresas')->insert(['id'=>'230', 'empresa'=>'AUTORIDAD DE FISCALIZACIÓN Y CONTROL SOCIAL DE BOSQUES Y TIERRA']);
        \DB::table('egp_empresas')->insert(['id'=>'231', 'empresa'=>'AUTORIDAD DE FISCALIZACIÓN Y CONTROL SOCIAL DE ELECTRICIDAD']);
        \DB::table('egp_empresas')->insert(['id'=>'232', 'empresa'=>'AUTORIDAD DE FISCALIZACIÓN Y CONTROL SOCIAL DE EMPRESAS']);
        \DB::table('egp_empresas')->insert(['id'=>'74', 'empresa'=>'AUTORIDAD DE IMPUGNACIÓN TRIBUTARIA -AIT']);
        \DB::table('egp_empresas')->insert(['id'=>'16', 'empresa'=>'AUTORIDAD DE REGULACION Y FISCALIZACION DE TELECOMUNICACIONES Y TRANSPORTES - ATT']);
        \DB::table('egp_empresas')->insert(['id'=>'18', 'empresa'=>'AUTORIDAD DE SUPERVISION DEL SISTEMA FINANCIERO - ASFI']);
        \DB::table('egp_empresas')->insert(['id'=>'62', 'empresa'=>'AUTORIDAD JURIDICCIONAL ADMINISTRATIVA MINERA']);
        \DB::table('egp_empresas')->insert(['id'=>'403', 'empresa'=>'AUTORIDAD PLURINACIONAL DE LA MADRE TIERRA']);
        \DB::table('egp_empresas')->insert(['id'=>'139', 'empresa'=>'AUTORIDAD Y FISCALIZACIóN Y CONTROL SOCIAL DEL JUEGO']);
        \DB::table('egp_empresas')->insert(['id'=>'177', 'empresa'=>'BANCO BISA S.A.']);
        \DB::table('egp_empresas')->insert(['id'=>'85', 'empresa'=>'BANCO CENTRAL DE BOLIVIA - BCB']);
        \DB::table('egp_empresas')->insert(['id'=>'397', 'empresa'=>'BANCO DE CREDITO']);
        \DB::table('egp_empresas')->insert(['id'=>'118', 'empresa'=>'BANCO DE DESARROLLO PRODUCTIVO - BDP']);
        \DB::table('egp_empresas')->insert(['id'=>'411', 'empresa'=>'BANCO DO BRASIL S.A. SUCURSAL BOLVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'390', 'empresa'=>'BANCO ECONOMICO S.A.']);
        \DB::table('egp_empresas')->insert(['id'=>'143', 'empresa'=>'BANCO GANADERO S.A.']);
        \DB::table('egp_empresas')->insert(['id'=>'389', 'empresa'=>'BANCO LOS ANDES PROCREDIT']);
        \DB::table('egp_empresas')->insert(['id'=>'142', 'empresa'=>'BANCO MERCANTIL SANTA CRUZ']);
        \DB::table('egp_empresas')->insert(['id'=>'191', 'empresa'=>'BANCO NACIONAL DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'178', 'empresa'=>'BANCO SOLIDARIO']);
        \DB::table('egp_empresas')->insert(['id'=>'117', 'empresa'=>'BANCO UNION S.A.']);
        \DB::table('egp_empresas')->insert(['id'=>'406', 'empresa'=>'BRIGADA PARLAMENTARIA DE COCHABAMBA']);
        \DB::table('egp_empresas')->insert(['id'=>'268', 'empresa'=>'BRIGADAS DE LA FUERZA AÉREA']);
        \DB::table('egp_empresas')->insert(['id'=>'63', 'empresa'=>'CAJA NACIONAL DE SALUD']);
        \DB::table('egp_empresas')->insert(['id'=>'269', 'empresa'=>'CAJA PETROLERA DE SALUD']);
        \DB::table('egp_empresas')->insert(['id'=>'270', 'empresa'=>'CAJA SOCIAL DE LAS COORPORACIONES DE DESARROLLO - CORDESS']);
        \DB::table('egp_empresas')->insert(['id'=>'7', 'empresa'=>'CAMARA DE DIPUTADOS']);
        \DB::table('egp_empresas')->insert(['id'=>'8', 'empresa'=>'CAMARA DE SENADORES']);
        \DB::table('egp_empresas')->insert(['id'=>'271', 'empresa'=>'CÁMARAS AGROPECUARIAS']);
        \DB::table('egp_empresas')->insert(['id'=>'272', 'empresa'=>'CÁMARAS BINACIONALES']);
        \DB::table('egp_empresas')->insert(['id'=>'273', 'empresa'=>'CÁMARAS HOTELERAS']);
        \DB::table('egp_empresas')->insert(['id'=>'274', 'empresa'=>'CAMARAS PUBLICITARIAS']);
        \DB::table('egp_empresas')->insert(['id'=>'153', 'empresa'=>'CAPACITACIÓN Y DERECHOS CIUDADANOS - CDC']);
        \DB::table('egp_empresas')->insert(['id'=>'220', 'empresa'=>'CEMACO LTDA.']);
        \DB::table('egp_empresas')->insert(['id'=>'224', 'empresa'=>'CENTRO DE NATURISMO ANDINO BOLIVIANO']);
        \DB::table('egp_empresas')->insert(['id'=>'211', 'empresa'=>'CENTRO DE SALUD VIRGEN DEL ROSARIO']);
        \DB::table('egp_empresas')->insert(['id'=>'108', 'empresa'=>'CENTROS DE DESARROLLO DE CAPACIDADES Y SERVICIO SOCIAL - CEDECASS']);
        \DB::table('egp_empresas')->insert(['id'=>'392', 'empresa'=>'COLEGIO MILITAR GUALBERTO VILLARROEL']);
        \DB::table('egp_empresas')->insert(['id'=>'275', 'empresa'=>'COLEGIOS DE ABOGADOS DE LA PAZ']);
        \DB::table('egp_empresas')->insert(['id'=>'276', 'empresa'=>'COMANDO DEPARTAMENTAL']);
        \DB::table('egp_empresas')->insert(['id'=>'277', 'empresa'=>'COMANDO GENERAL DE LA FUERZA AÉREA']);
        \DB::table('egp_empresas')->insert(['id'=>'278', 'empresa'=>'COMANDO GENERAL DE LA FUERZA NAVAL']);
        \DB::table('egp_empresas')->insert(['id'=>'279', 'empresa'=>'COMANDO GENERAL DE LA POLICÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'280', 'empresa'=>'COMANDO GENERAL DE LAS FUERZAS ARMADAS']);
        \DB::table('egp_empresas')->insert(['id'=>'281', 'empresa'=>'COMANDO GENERAL DEL EJÉRCITO']);
        \DB::table('egp_empresas')->insert(['id'=>'282', 'empresa'=>'COMITÉS CÍVICOS']);
        \DB::table('egp_empresas')->insert(['id'=>'80', 'empresa'=>'CONCEJO MUNICIPAL DE COCHABAMBA']);
        \DB::table('egp_empresas')->insert(['id'=>'283', 'empresa'=>'CONFEDERACIÓN DE EMPRESARIOS PRIVADOS DE BOLIVIA - CEPB']);
        \DB::table('egp_empresas')->insert(['id'=>'217', 'empresa'=>'CONSEJO DEPARTAMENTAL DE MEDICINA TRADICIONAL']);
        \DB::table('egp_empresas')->insert(['id'=>'284', 'empresa'=>'CONTRALORÍA GENERAL DEL ESTADO - CGE']);
        \DB::table('egp_empresas')->insert(['id'=>'146', 'empresa'=>'COOPERATIVA DE TELÉFONOS LTDA. - LA PAZ']);
        \DB::table('egp_empresas')->insert(['id'=>'285', 'empresa'=>'CORPORACIÓN MINERA DE BOLIVIA - COMIBOL']);
        \DB::table('egp_empresas')->insert(['id'=>'286', 'empresa'=>'CORTE CONSEJO DE LA JUDICATURA']);
        \DB::table('egp_empresas')->insert(['id'=>'288', 'empresa'=>'CORTES SUPERIORES DE DISTRITO']);
        \DB::table('egp_empresas')->insert(['id'=>'287', 'empresa'=>'CORTE SUPREMA DE JUSTICIA']);
        \DB::table('egp_empresas')->insert(['id'=>'289', 'empresa'=>'DEFENSA CIVIL']);
        \DB::table('egp_empresas')->insert(['id'=>'290', 'empresa'=>'DEFENSA DEL CONSUMIDOR']);
        \DB::table('egp_empresas')->insert(['id'=>'51', 'empresa'=>'DEFENSORIA DEL PUEBLO']);
        \DB::table('egp_empresas')->insert(['id'=>'291', 'empresa'=>'DEPOSITOS ADUANEROS BOLIVIANOS - DAB']);
        \DB::table('egp_empresas')->insert(['id'=>'391', 'empresa'=>'Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH']);
        \DB::table('egp_empresas')->insert(['id'=>'14', 'empresa'=>'DIMA LTDA']);
        \DB::table('egp_empresas')->insert(['id'=>'184', 'empresa'=>'DIRECCION DEPARTAMENTAL DE EDUCACION']);
        \DB::table('egp_empresas')->insert(['id'=>'89', 'empresa'=>'DIRECCIÓN GENERAL DE AERONAUTA CIVIL']);
        \DB::table('egp_empresas')->insert(['id'=>'401', 'empresa'=>'EJERCITO DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'186', 'empresa'=>'EMBOTELLADORAS BOLIVIANAS UNIDAS - EMBOL']);
        \DB::table('egp_empresas')->insert(['id'=>'79', 'empresa'=>'EMPRESA BOLIVIANA DE ALMENDRA Y DERIVADOS']);
        \DB::table('egp_empresas')->insert(['id'=>'130', 'empresa'=>'EMPRESA DE APOYO A LA PRODUCCIÓN DE ALIMENTO - EMAPA']);
        \DB::table('egp_empresas')->insert(['id'=>'292', 'empresa'=>'EMPRESA DE CORREOS DE BOLIVIA - ECOBOL']);
        \DB::table('egp_empresas')->insert(['id'=>'160', 'empresa'=>'EMPRESA ESTATAL DE TELEVISIÓN - BOLIVIATV']);
        \DB::table('egp_empresas')->insert(['id'=>'131', 'empresa'=>'EMPRESA ESTATAL DE TRANSPORTE POR CABLE - MITELEFERICO']);
        \DB::table('egp_empresas')->insert(['id'=>'159', 'empresa'=>'EMPRESA MUNICIPAL DE ASALTO Y VIAS - EMAVIAS']);
        \DB::table('egp_empresas')->insert(['id'=>'394', 'empresa'=>'EMPRESA NACIONAL DE ELECTRICIDAD BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'41', 'empresa'=>'EMPRESA NACIONAL DE TELECOMUNICACIONES - ENTEL']);
        \DB::table('egp_empresas')->insert(['id'=>'170', 'empresa'=>'EMPRESA NACIONAL TEXTIL - ENATEX']);
        \DB::table('egp_empresas')->insert(['id'=>'412', 'empresa'=>'EMPRESA PÚBLICA NACIONAL ESTRATÉGICA BOLIVIANA DE AVIACIÓN - BOA']);
        \DB::table('egp_empresas')->insert(['id'=>'83', 'empresa'=>'EMPRESA PÚBLICA PRODUCTIVA LACTEOS DE BOLIVIA - LACTEOSBOL']);
        \DB::table('egp_empresas')->insert(['id'=>'179', 'empresa'=>'EMPRESA PÚBLICA QUIPUS']);
        \DB::table('egp_empresas')->insert(['id'=>'15', 'empresa'=>'ESCUELA DE GESTION PUBLICA PLURINACIONAL']);
        \DB::table('egp_empresas')->insert(['id'=>'152', 'empresa'=>'ESCUELA DE JUECES DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'404', 'empresa'=>'ESCUELA INDUSTRIAL SUPERIOR PEDRO DOMINGO MURILLO']);
        \DB::table('egp_empresas')->insert(['id'=>'135', 'empresa'=>'ESCUELA LATINOAMERICANA DE MEDICINA']);
        \DB::table('egp_empresas')->insert(['id'=>'162', 'empresa'=>'ESCUELA MILITAR DE INGENIERIA - EMI']);
        \DB::table('egp_empresas')->insert(['id'=>'123', 'empresa'=>'ESCUELA SUPERIOR DE FORMACIÓN DE MAESTROS FRANZ TAMAYO']);
        \DB::table('egp_empresas')->insert(['id'=>'82', 'empresa'=>'ESCUELA SUPERIOR DE FORMACIÓN DE MAESTROS SIMÓN BOLIVAR']);
        \DB::table('egp_empresas')->insert(['id'=>'398', 'empresa'=>'FEDERACIÓN DE TRABAJADORES DE LA PRENSA']);
        \DB::table('egp_empresas')->insert(['id'=>'293', 'empresa'=>'FEDERACIONES DE COOPERATIVAS DE TELECOMUNICACIONES']);
        \DB::table('egp_empresas')->insert(['id'=>'294', 'empresa'=>'FEDERACIONES DE GANADEROS']);
        \DB::table('egp_empresas')->insert(['id'=>'295', 'empresa'=>'FEDERACIONES DE LA MICRO Y PEQUEÑA EMPRESA']);
        \DB::table('egp_empresas')->insert(['id'=>'298', 'empresa'=>'FEDERACIONES DEPORTIVAS']);
        \DB::table('egp_empresas')->insert(['id'=>'296', 'empresa'=>'FEDERACIONES DE PROFESIONALES']);
        \DB::table('egp_empresas')->insert(['id'=>'297', 'empresa'=>'FEDERACIONES DE TRABAJADORAS DEL HOGAR']);
        \DB::table('egp_empresas')->insert(['id'=>'299', 'empresa'=>'FEDERACIONES EMPRESARIALES DEPARTAMENTALES']);
        \DB::table('egp_empresas')->insert(['id'=>'300', 'empresa'=>'FEDERACIONES MINERAS']);
        \DB::table('egp_empresas')->insert(['id'=>'301', 'empresa'=>'FISCALIA GENERAL']);
        \DB::table('egp_empresas')->insert(['id'=>'302', 'empresa'=>'FISCALÍAS DE DISTRITO']);
        \DB::table('egp_empresas')->insert(['id'=>'388', 'empresa'=>'FONDO DE DESARROLLO INDIGENA']);
        \DB::table('egp_empresas')->insert(['id'=>'303', 'empresa'=>'FONDO NACIONAL DE DESARROLLO REGIONAL - FNDR']);
        \DB::table('egp_empresas')->insert(['id'=>'304', 'empresa'=>'FONDO NACIONAL DE INVERSIÓN PRODUCTIVA Y SOCIAL - FPS']);
        \DB::table('egp_empresas')->insert(['id'=>'400', 'empresa'=>'FUERZA AEREA BOLIVIANA']);
        \DB::table('egp_empresas')->insert(['id'=>'161', 'empresa'=>'FUNDACIÓN PRO MUJER']);
        \DB::table('egp_empresas')->insert(['id'=>'305', 'empresa'=>'FUNDEMPRESA']);
        \DB::table('egp_empresas')->insert(['id'=>'49', 'empresa'=>'GACETA OFICIAL DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'233', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE BENI']);
        \DB::table('egp_empresas')->insert(['id'=>'234', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE CHUQUISACA']);
        \DB::table('egp_empresas')->insert(['id'=>'105', 'empresa'=>'GOBIERNO AUTONOMO DEPARTAMENTAL DE COCHABAMBA']);
        \DB::table('egp_empresas')->insert(['id'=>'5', 'empresa'=>'GOBIERNO AUTONOMO DEPARTAMENTAL DE  LA PAZ']);
        \DB::table('egp_empresas')->insert(['id'=>'57', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE ORURO']);
        \DB::table('egp_empresas')->insert(['id'=>'235', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE PANDO']);
        \DB::table('egp_empresas')->insert(['id'=>'236', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE POTOSÍ']);
        \DB::table('egp_empresas')->insert(['id'=>'237', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE SANTA CRUZ']);
        \DB::table('egp_empresas')->insert(['id'=>'81', 'empresa'=>'GOBIERNO AUTÓNOMO DEPARTAMENTAL DE TARIJA']);
        \DB::table('egp_empresas')->insert(['id'=>'402', 'empresa'=>'GOBIERNO AUTÓNOMO MUNICIPAL DE EL ALTO']);
        \DB::table('egp_empresas')->insert(['id'=>'6', 'empresa'=>'GOBIERNOS AUTÓNOMOS MUNICIPALES DE CIUDADES CAPITALES']);
        \DB::table('egp_empresas')->insert(['id'=>'124', 'empresa'=>'GOBIERNOS AUTÓNOMOS MUNICIPALES RURALES']);
        \DB::table('egp_empresas')->insert(['id'=>'13', 'empresa'=>'HIGH TECHNOLOGIES']);
        \DB::table('egp_empresas')->insert(['id'=>'225', 'empresa'=>'HOSPITAL DANIEL BRACAMONTE']);
        \DB::table('egp_empresas')->insert(['id'=>'188', 'empresa'=>'HOSPITAL GENERAL SAN JUAN DE DIOS']);
        \DB::table('egp_empresas')->insert(['id'=>'120', 'empresa'=>'HOSPITAL GINECO OBSTETRICO NEONATAL']);
        \DB::table('egp_empresas')->insert(['id'=>'212', 'empresa'=>'HOSPITAL LEO SCHWARZ']);
        \DB::table('egp_empresas')->insert(['id'=>'116', 'empresa'=>'HOSPITAL MUNICIPAL DE VIACHA']);
        \DB::table('egp_empresas')->insert(['id'=>'213', 'empresa'=>'HOSPITAL NICOLAS ORTIZ']);
        \DB::table('egp_empresas')->insert(['id'=>'195', 'empresa'=>'HOSPITAL SAN ROQUE']);
        \DB::table('egp_empresas')->insert(['id'=>'208', 'empresa'=>'HOSPITAL TOMINA']);
        \DB::table('egp_empresas')->insert(['id'=>'144', 'empresa'=>'HOSPITAL UNIVERSITARIO JAPONÉS']);
        \DB::table('egp_empresas')->insert(['id'=>'306', 'empresa'=>'INSTITUCIONES DE SERVICIOS DE LAS FFAA']);
        \DB::table('egp_empresas')->insert(['id'=>'77', 'empresa'=>'INSTITUTO BOLIIANO DE METROLOGIA - IBMETRO']);
        \DB::table('egp_empresas')->insert(['id'=>'72', 'empresa'=>'INSTITUTO BOLIVIANO DE CEGUERA - IBCBOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'132', 'empresa'=>'INSTITUTO DE CAPACITACIÓN DEL ORIENTE - ICO']);
        \DB::table('egp_empresas')->insert(['id'=>'70', 'empresa'=>'INSTITUTO DEL SEGURO AGRARIO - INSA']);
        \DB::table('egp_empresas')->insert(['id'=>'42', 'empresa'=>'INSTITUTO NACIONAL DE ESTADÍSTICA - INE']);
        \DB::table('egp_empresas')->insert(['id'=>'75', 'empresa'=>'INSTITUTO NACIONAL DE REFORMA AGRARIA - INRA']);
        \DB::table('egp_empresas')->insert(['id'=>'73', 'empresa'=>'INSTITUTO NACIONAL DE SALUD OCUPACIONAL - INSO']);
        \DB::table('egp_empresas')->insert(['id'=>'387', 'empresa'=>'INSTITUTO NACIONAL DE SEGUROS DE SALUD']);
        \DB::table('egp_empresas')->insert(['id'=>'113', 'empresa'=>'INSTITUTO POLITECNICO TUPAK KATARI']);
        \DB::table('egp_empresas')->insert(['id'=>'307', 'empresa'=>'INSTITUTOS DE FORMACIÓN POLICIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'308', 'empresa'=>'INSTITUTOS MILITARES DE LA FUERZA AÉREA']);
        \DB::table('egp_empresas')->insert(['id'=>'309', 'empresa'=>'INSTITUTOS MILITARES DE LA FUERZA NAVAL']);
        \DB::table('egp_empresas')->insert(['id'=>'310', 'empresa'=>'INSTITUTOS MILITARES DEL EJÉRCITO']);
        \DB::table('egp_empresas')->insert(['id'=>'190', 'empresa'=>'INSTITUTO SUPERIOR JESÚS MARIA I']);
        \DB::table('egp_empresas')->insert(['id'=>'187', 'empresa'=>'INSTITUTO SUPERIOR JESÚS MARIA II']);
        \DB::table('egp_empresas')->insert(['id'=>'150', 'empresa'=>'INSTITUTO SUPERIOR SANTO TORIBIO DE MOGROVEJO - ISEIT']);
        \DB::table('egp_empresas')->insert(['id'=>'175', 'empresa'=>'INSTITUTO TECNOLOGICO DON BOSCO']);
        \DB::table('egp_empresas')->insert(['id'=>'198', 'empresa'=>'KALLAWAYAS SIN FRONTERAS - KASFRO']);
        \DB::table('egp_empresas')->insert(['id'=>'395', 'empresa'=>'KURMI - APOYO AL DESARROLLO SOSTENIBLE INTERANDINO']);
        \DB::table('egp_empresas')->insert(['id'=>'174', 'empresa'=>'LINEA AEREA ECOJET S.A.']);
        \DB::table('egp_empresas')->insert(['id'=>'121', 'empresa'=>'MAGISTERIO DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'311', 'empresa'=>'MINISTERIO DE AUTONOMÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'312', 'empresa'=>'MINISTERIO DE COMUNICACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'43', 'empresa'=>' MINISTERIO DE CURLTURAS Y TURISMO']);
        \DB::table('egp_empresas')->insert(['id'=>'114', 'empresa'=>'MINISTERIO DE DEFENSA DEL ESTADO PLURINACIONAL DE BOLIVIA - MINDEF']);
        \DB::table('egp_empresas')->insert(['id'=>'313', 'empresa'=>'MINISTERIO DE DEFENSA LEGAL DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'45', 'empresa'=>'MINISTERIO DE DESARROLLO PRODUCTIVO Y ECONOMÍA PLURAL - MDPYEP']);
        \DB::table('egp_empresas')->insert(['id'=>'180', 'empresa'=>'MINISTERIO DE DESARROLLO RURAL Y TIERRAS']);
        \DB::table('egp_empresas')->insert(['id'=>'50', 'empresa'=>'MINISTERIO DE ECONOMÍA Y FINANZAS PÚBLICAS']);
        \DB::table('egp_empresas')->insert(['id'=>'1', 'empresa'=>'MINISTERIO DE EDUCACION - MINEDU']);
        \DB::table('egp_empresas')->insert(['id'=>'129', 'empresa'=>'MINISTERIO DE ENERGIAS']);
        \DB::table('egp_empresas')->insert(['id'=>'314', 'empresa'=>'MINISTERIO DE GOBIERNO']);
        \DB::table('egp_empresas')->insert(['id'=>'410', 'empresa'=>'MINISTERIO DE HIDROCARBUROS']);
        \DB::table('egp_empresas')->insert(['id'=>'96', 'empresa'=>'MINISTERIO DE JUSTICIA Y TRANSPARENCIA INSTITUCIONAL']);
        \DB::table('egp_empresas')->insert(['id'=>'4', 'empresa'=>'MINISTERIO DE LA PRESIDENCIA']);
        \DB::table('egp_empresas')->insert(['id'=>'138', 'empresa'=>'MINISTERIO DE MEDIO AMBIENTE Y AGUAS']);
        \DB::table('egp_empresas')->insert(['id'=>'315', 'empresa'=>'MINISTERIO DE MINERÍA Y METALURGIA']);
        \DB::table('egp_empresas')->insert(['id'=>'2', 'empresa'=>'MINISTERIO DE OBRAS PUBLICAS, SERVICIOS  Y VIVIENDA - MOPSV']);
        \DB::table('egp_empresas')->insert(['id'=>'54', 'empresa'=>'MINISTERIO DE PLANIFICACIÓN DEL DESARROLLO']);
        \DB::table('egp_empresas')->insert(['id'=>'92', 'empresa'=>'MINISTERIO DE RELACIONES EXTERIORES']);
        \DB::table('egp_empresas')->insert(['id'=>'44', 'empresa'=>'MINISTERIO DE SALUD Y DEPORTES']);
        \DB::table('egp_empresas')->insert(['id'=>'66', 'empresa'=>'MINISTERIO DE TRABAJO, EMPLEO Y PREVISIÓN SOCIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'61', 'empresa'=>'MINISTERIO DE TRANSPARENCIA INSTITUCIONAL Y LUCHA CONTRA LA CORRUPCIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'0', 'empresa'=>'NO CUENTA CON EMPRESA/INSTITUCION']);
        \DB::table('egp_empresas')->insert(['id'=>'316', 'empresa'=>'NOTARIAS DE FE PÚBLICA']);
        \DB::table('egp_empresas')->insert(['id'=>'318', 'empresa'=>'ORGANISMOS DE ASESORAMIENTO Y APOYO']);
        \DB::table('egp_empresas')->insert(['id'=>'319', 'empresa'=>'ORGANISMOS DESCENTRALIZADOS']);
        \DB::table('egp_empresas')->insert(['id'=>'320', 'empresa'=>'ORGANISMOS INTERNACIONALES']);
        \DB::table('egp_empresas')->insert(['id'=>'321', 'empresa'=>'ORGANISMOS NO GUBERNAMENTALES (ONGS)']);
        \DB::table('egp_empresas')->insert(['id'=>'322', 'empresa'=>'ORGANISMOS OPERATIVOS']);
        \DB::table('egp_empresas')->insert(['id'=>'156', 'empresa'=>'ORGANIZACIÓN DE MUJERES AYMARAS DEL KOLLASUYO - OMAK']);
        \DB::table('egp_empresas')->insert(['id'=>'323', 'empresa'=>'ORGANIZACIONES CAMPESINAS E INDÍGENAS']);
        \DB::table('egp_empresas')->insert(['id'=>'324', 'empresa'=>'ORGANIZACIONES FOLKLÓRICAS Y MUSICALES FRATERNIDADES Y COMPARSAS']);
        \DB::table('egp_empresas')->insert(['id'=>'325', 'empresa'=>'ORGANIZACIONES TERRITORIALES DE BASE (OTBS)']);
        \DB::table('egp_empresas')->insert(['id'=>'157', 'empresa'=>'ORGANO JUDICIAL DE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'90', 'empresa'=>'OTROS']);
        \DB::table('egp_empresas')->insert(['id'=>'167', 'empresa'=>'POLICIA BOLIVIANA']);
        \DB::table('egp_empresas')->insert(['id'=>'326', 'empresa'=>'PRESIDENCIA DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'12', 'empresa'=>'PROCURADURÍA GENERAL DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'327', 'empresa'=>'PROGRAMA NACIONAL DE SEMILLAS - PNS']);
        \DB::table('egp_empresas')->insert(['id'=>'10', 'empresa'=>'PROGRAMA PARA EL DESARROLLO DE LAS NACIONES UNIDAS EN BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'78', 'empresa'=>'PROMIEL']);
        \DB::table('egp_empresas')->insert(['id'=>'169', 'empresa'=>'PROMUEVE BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'53', 'empresa'=>'REGISTRO INTERNACIONAL BOLIVIANO DE BUQUES']);
        \DB::table('egp_empresas')->insert(['id'=>'94', 'empresa'=>'REGISTRO UNICO PARA LA ADMINISTRACIÓN TRIBUTARÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'104', 'empresa'=>'SERVICIO DE DESARROLLO DE LAS EMPRESAS PÚBLICAS PRODUCTIVAS - SEDES']);
        \DB::table('egp_empresas')->insert(['id'=>'52', 'empresa'=>'SERVICIO DE IMPUESTOS NACIONALES - SIN']);
        \DB::table('egp_empresas')->insert(['id'=>'59', 'empresa'=>'SERVICIO DEPARTAMENTAL DE SALUD']);
        \DB::table('egp_empresas')->insert(['id'=>'328', 'empresa'=>'SERVICIO DE REGISTRO CIVIL - SERECI']);
        \DB::table('egp_empresas')->insert(['id'=>'145', 'empresa'=>'SERVICIO ESTATAL DE AUTONOMÍAS - SEA']);
        \DB::table('egp_empresas')->insert(['id'=>'164', 'empresa'=>'SERVICIO GENERAL DE IDENTIFICACIÓN PERSONAL - SEGIP']);
        \DB::table('egp_empresas')->insert(['id'=>'69', 'empresa'=>'SERVICIO NACIONAL DEL SISTEMA DE REPARTO - SENASIR']);
        \DB::table('egp_empresas')->insert(['id'=>'332', 'empresa'=>'SERVICIO NACIONAL DEL SISTEMA DE REPARTO - SENASIR']);
        \DB::table('egp_empresas')->insert(['id'=>'329', 'empresa'=>'SERVICIO NACIONAL DE MIGRACIÓN - SENAMIG']);
        \DB::table('egp_empresas')->insert(['id'=>'133', 'empresa'=>'SERVICIO NACIONAL DE PATRIMONIO DEL ESTADO - SENAPE']);
        \DB::table('egp_empresas')->insert(['id'=>'84', 'empresa'=>'SERVICIO NACIONAL DE PROPIEDAD INTELECTUAL - SENAPI']);
        \DB::table('egp_empresas')->insert(['id'=>'409', 'empresa'=>'SERVICIO NACIONAL DE REGISTRO Y CONTROL DE LA COMERCIALIZACIÓN DE MINERALES Y METALES']);
        \DB::table('egp_empresas')->insert(['id'=>'330', 'empresa'=>'SERVICIO NACIONAL DE SANIDAD AGROPECUARIA E INOCUIDAD ALIMENTARIA - SENASAG']);
        \DB::table('egp_empresas')->insert(['id'=>'331', 'empresa'=>'SERVICIO NACIONAL DE VERIFICACIÓN DE EXPORTACIONES - SENAVEX']);
        \DB::table('egp_empresas')->insert(['id'=>'119', 'empresa'=>'SERVICIO NACIONAL PARA LA SOSTENIBILIDAD DE SERVICIOS EN SANEAMIENTO BÁSICO - SENASBA']);
        \DB::table('egp_empresas')->insert(['id'=>'413', 'empresa'=>'SERVICIO NACIONAL TEXTIL-SENATEX']);
        \DB::table('egp_empresas')->insert(['id'=>'386', 'empresa'=>'SINDEFINIR']);
        \DB::table('egp_empresas')->insert(['id'=>'199', 'empresa'=>'SOCIEDAD BOLIVIANA DE MEDICINA TRADICIONAL - SOBOMETRA']);
        \DB::table('egp_empresas')->insert(['id'=>'333', 'empresa'=>'SOCIEDADES DE INGENIEROS - SIB']);
        \DB::table('egp_empresas')->insert(['id'=>'334', 'empresa'=>'TELEFONÍA Y TELECOMUNICACIONES']);
        \DB::table('egp_empresas')->insert(['id'=>'47', 'empresa'=>'TRIBUNAL CONSTITUCIONAL PLURINACIONAL - TCP']);
        \DB::table('egp_empresas')->insert(['id'=>'317', 'empresa'=>'TRIBUNALES ELECTORALES DEPARTAMENTALES']);
        \DB::table('egp_empresas')->insert(['id'=>'165', 'empresa'=>'TRIBUNAL SUPREMO ELECTORAL - OEP']);
        \DB::table('egp_empresas')->insert(['id'=>'11', 'empresa'=>'UNICEF BOLIVIA']);
        \DB::table('egp_empresas')->insert(['id'=>'97', 'empresa'=>'UNIDAD DE INVESTIGACIONES FINANCIERAS - UIF']);
        \DB::table('egp_empresas')->insert(['id'=>'197', 'empresa'=>'UNIDAD DE MEDICINA TRADICIONAL E INTERCULTURALIDAD - UNIMETRA']);
        \DB::table('egp_empresas')->insert(['id'=>'76', 'empresa'=>'UNIDAD EJECUTORA DE LUCHA INTEGRAL CONTRA EL NARCOTRAFICO - UELICN']);
        \DB::table('egp_empresas')->insert(['id'=>'65', 'empresa'=>'UNIDADES EDUCATIVAS']);
        \DB::table('egp_empresas')->insert(['id'=>'247', 'empresa'=>'UNIVERSIDAD AMAZÓNICA DE PANDO - UADP']);
        \DB::table('egp_empresas')->insert(['id'=>'243', 'empresa'=>'UNIVERSIDAD AUTÓNOMA GABRIEL RENÉ MORENO - UAGRM']);
        \DB::table('egp_empresas')->insert(['id'=>'173', 'empresa'=>'UNIVERSIDAD AUTÓNOMA JUAN MISAEL SARACHO - UAJMS']);
        \DB::table('egp_empresas')->insert(['id'=>'248', 'empresa'=>'UNIVERSIDAD CATÓLICA BOLIVIANA SAN PABLO - UCSP']);
        \DB::table('egp_empresas')->insert(['id'=>'250', 'empresa'=>'UNIVERSIDAD DE AQUINO BOLIVIA - UDABOL']);
        \DB::table('egp_empresas')->insert(['id'=>'396', 'empresa'=>'UNIVERSIDAD INDIGENA BOLIVIANA AYMARA - TUPAK KATARI']);
        \DB::table('egp_empresas')->insert(['id'=>'252', 'empresa'=>'UNIVERSIDAD LA SALLE - UNIVSA']);
        \DB::table('egp_empresas')->insert(['id'=>'253', 'empresa'=>'UNIVERSIDAD LOYOLA']);
        \DB::table('egp_empresas')->insert(['id'=>'241', 'empresa'=>'UNIVERSIDAD MAYOR DE SAN ANDRÉS - UMSA']);
        \DB::table('egp_empresas')->insert(['id'=>'242', 'empresa'=>'UNIVERSIDAD MAYOR DE SAN SIMÓN - UMSS']);
        \DB::table('egp_empresas')->insert(['id'=>'110', 'empresa'=>'UNIVERSIDAD MAYOR REAL Y PONTIFICIA SAN FRANCISCO XAVIER - USFX']);
        \DB::table('egp_empresas')->insert(['id'=>'246', 'empresa'=>'UNIVERSIDAD NACIONAL SIGLO XX - UNSXX']);
        \DB::table('egp_empresas')->insert(['id'=>'251', 'empresa'=>'UNIVERSIDAD NUR - NUR']);
        \DB::table('egp_empresas')->insert(['id'=>'249', 'empresa'=>'UNIVERSIDAD PRIVADA DEL VALLE - UNIVALLE']);
        \DB::table('egp_empresas')->insert(['id'=>'147', 'empresa'=>'UNIVERSIDAD PÚBLICA EL ALTO - UPEA']);
        \DB::table('egp_empresas')->insert(['id'=>'245', 'empresa'=>'UNIVERSIDAD TÉCNICA DEL BENI - UTBN']);
        \DB::table('egp_empresas')->insert(['id'=>'60', 'empresa'=>'UNIVERSIDAD TÉCNICA DE ORURO - UTO']);
        \DB::table('egp_empresas')->insert(['id'=>'244', 'empresa'=>'UNIVERSIDAD TOMÁS FRIAS - UTF']);
        \DB::table('egp_empresas')->insert(['id'=>'336', 'empresa'=>'VICEMIN. DE AGUA POTABLE Y SANEAMIENTO BÁSICO']);
        \DB::table('egp_empresas')->insert(['id'=>'337', 'empresa'=>'VICEMIN. DE AUTONOMÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'338', 'empresa'=>'VICEMIN. DE CIENCIA Y TECNOLOGÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'339', 'empresa'=>'VICEMIN. DE COCA Y DESARROLLO INTEGRAL']);
        \DB::table('egp_empresas')->insert(['id'=>'171', 'empresa'=>'VICEMIN. DE COMERCIO INTERNO Y EXPORTACION - VCE']);
        \DB::table('egp_empresas')->insert(['id'=>'340', 'empresa'=>'VICEMIN. DE COOPERATIVAS MINERAS']);
        \DB::table('egp_empresas')->insert(['id'=>'335', 'empresa'=>'VICEMIN. DE COORD. CON MOVIMIENTOS SOCIALES Y SOCIEDAD CIVIL']);
        \DB::table('egp_empresas')->insert(['id'=>'341', 'empresa'=>'VICEMIN. DE COORDINACIÓN GESTION GUBERNAMENTAL Y TERRITORIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'342', 'empresa'=>'VICEMIN. DE DEFENSA CIVIL']);
        \DB::table('egp_empresas')->insert(['id'=>'343', 'empresa'=>'VICEMIN. DE DEFENSA DE LOS DERECHOS DEL USUARIO Y CONSUMIDOR']);
        \DB::table('egp_empresas')->insert(['id'=>'344', 'empresa'=>'VICEMIN. DE DEFENSA LEGAL DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'345', 'empresa'=>'VICEMIN. DE DEFENSA SOCIAL Y SUSTANCIAS CONTROLADAS']);
        \DB::table('egp_empresas')->insert(['id'=>'346', 'empresa'=>'VICEMIN. DE DEFENSA Y COOPERACIÓN AL DESARROLLO INTEGRAL']);
        \DB::table('egp_empresas')->insert(['id'=>'347', 'empresa'=>'VICEMIN. DE DEPORTES']);
        \DB::table('egp_empresas')->insert(['id'=>'348', 'empresa'=>'VICEMIN. DE DESARROLLO ENERGÉTICO - VMDE']);
        \DB::table('egp_empresas')->insert(['id'=>'349', 'empresa'=>'VICEMIN. DE DESARROLLO PRODUCTIVO MINERO METALÚRGICO']);
        \DB::table('egp_empresas')->insert(['id'=>'148', 'empresa'=>'VICEMIN. DE DESARROLLO RURAL Y AGROPECUARIO']);
        \DB::table('egp_empresas')->insert(['id'=>'350', 'empresa'=>'VICEMIN. DE DESCOLONIZACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'351', 'empresa'=>'VICEMIN. DE EDUCACIÓN ALTERNATIVA Y ESPECIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'352', 'empresa'=>'VICEMIN. DE EDUCACIÓN REGULAR']);
        \DB::table('egp_empresas')->insert(['id'=>'353', 'empresa'=>'VICEMIN. DE EDUCACIÓN SUPERIOR DE FORMACIÓN PROFESIONAL']);
        \DB::table('egp_empresas')->insert(['id'=>'354', 'empresa'=>'VICEMIN. DE ELECTRICIDAD Y ENERGÍAS ALTERNATIVAS - VMEEA']);
        \DB::table('egp_empresas')->insert(['id'=>'355', 'empresa'=>'VICEMIN. DE EMPLEO, SERVICIO CIVIL Y COOPERATIVAS']);
        \DB::table('egp_empresas')->insert(['id'=>'356', 'empresa'=>'VICEMIN. DE EXPLORACIÓN Y EXPLOTACIÓN DE HIDROCARBUROS - VMEEH']);
        \DB::table('egp_empresas')->insert(['id'=>'357', 'empresa'=>'VICEMIN. DE GESTIÓN INSTITUCIONAL']);
        \DB::table('egp_empresas')->insert(['id'=>'358', 'empresa'=>'VICEMIN. DE IGUALDAD DE OPORTUNIDADES']);
        \DB::table('egp_empresas')->insert(['id'=>'359', 'empresa'=>'VICEMIN. DE INTERCULTURALIDAD']);
        \DB::table('egp_empresas')->insert(['id'=>'360', 'empresa'=>'VICEMIN. DE INVERSIÓN PÚBLICA Y FINANCIAMIENTO EXTERNO']);
        \DB::table('egp_empresas')->insert(['id'=>'361', 'empresa'=>'VICEMIN. DE JUSTICIA INDÍGENA ORIGINARIO CAMPESINA']);
        \DB::table('egp_empresas')->insert(['id'=>'362', 'empresa'=>'VICEMIN. DE JUSTICIA Y DERECHOS FUNDAMENTALES']);
        \DB::table('egp_empresas')->insert(['id'=>'363', 'empresa'=>'VICEMIN. DE LA INDUSTRIA DEL TURISMO']);
        \DB::table('egp_empresas')->insert(['id'=>'385', 'empresa'=>'VICEMIN. DEL TESORO Y CRÉDITO PUBLICO']);
        \DB::table('egp_empresas')->insert(['id'=>'364', 'empresa'=>'VICEMIN. DE LUCHA CONTRA LA CORRUPCIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'365', 'empresa'=>'VICEMIN. DE MEDIO AMBIENTE, BIODIVERSIDAD Y CAMBIOS CLIMÁTICOS']);
        \DB::table('egp_empresas')->insert(['id'=>'168', 'empresa'=>'VICEMIN. DE MICRO Y PEQUEÑA EMPRESA']);
        \DB::table('egp_empresas')->insert(['id'=>'366', 'empresa'=>'VICEMIN. DE PENSIONES Y SERVICIOS FINANCIEROS']);
        \DB::table('egp_empresas')->insert(['id'=>'367', 'empresa'=>'VICEMIN. DE PLANIFICACIÓN ESTRATÉGICA DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'368', 'empresa'=>'VICEMIN. DE PLANIFICACIÓN Y COORDINACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'369', 'empresa'=>'VICEMIN. DE POLÍTICA MINERA, REGULACIÓN Y FISCALIZACIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'370', 'empresa'=>'VICEMIN. DE POLÍTICA TRIBUTARIA']);
        \DB::table('egp_empresas')->insert(['id'=>'371', 'empresa'=>'VICEMIN. DE PRESUPUESTO Y CONTABILIDAD FISCAL']);
        \DB::table('egp_empresas')->insert(['id'=>'372', 'empresa'=>'VICEMIN. DE PREVENCIÓN, PROMOCIÓN DE ÉTICA Y TRANSPARENCIA']);
        \DB::table('egp_empresas')->insert(['id'=>'373', 'empresa'=>'VICEMIN. DE PRODUCCIÓN INDUSTRIAL A MEDIANA Y GRAN ESCALA']);
        \DB::table('egp_empresas')->insert(['id'=>'374', 'empresa'=>'VICEMIN. DE RECURSOS HÍDRICOS Y RIEGO']);
        \DB::table('egp_empresas')->insert(['id'=>'375', 'empresa'=>'VICEMIN. DE RÉGIMEN INTERIOR Y POLICÍA']);
        \DB::table('egp_empresas')->insert(['id'=>'376', 'empresa'=>'VICEMIN. DE RELACIONES ECONÓMICAS Y COMERCIO EXTERIOR']);
        \DB::table('egp_empresas')->insert(['id'=>'377', 'empresa'=>'VICEMIN. DE RELACIONES EXTERIORES']);
        \DB::table('egp_empresas')->insert(['id'=>'378', 'empresa'=>'VICEMIN. DE SALUD Y PROMOCIÓN']);
        \DB::table('egp_empresas')->insert(['id'=>'379', 'empresa'=>'VICEMIN. DE SEGURIDAD CIUDADANA']);
        \DB::table('egp_empresas')->insert(['id'=>'380', 'empresa'=>'VICEMIN. DE TELECOMUNICACIONES']);
        \DB::table('egp_empresas')->insert(['id'=>'381', 'empresa'=>'VICEMIN. DE TIERRAS']);
        \DB::table('egp_empresas')->insert(['id'=>'382', 'empresa'=>'VICEMIN. DE TRABAJO Y PREVISIÓN SOCIAL']);
        \DB::table('egp_empresas')->insert(['id'=>'383', 'empresa'=>'VICEMIN. DE TRANSPORTES']);
        \DB::table('egp_empresas')->insert(['id'=>'384', 'empresa'=>'VICEMIN. DE VIVIENDA']);
        \DB::table('egp_empresas')->insert(['id'=>'3', 'empresa'=>'VICE PRESIDENCIA DEL ESTADO']);
        \DB::table('egp_empresas')->insert(['id'=>'134', 'empresa'=>'YACIMIENTOS PETROLÍFEROS FISCALES BOLIVIANOS - YPFB']);

    }
}
